export type CREATE_ARTIST_START = "CREATE_ARTIST_START";
export type CREATE_ARTIST_SUCCESS = "CREATE_ARTIST_SUCCESS";
export type CREATE_ARTIST_FAIL = "CREATE_ARTIST_FAIL";

export const CREATE_ARTIST_START: CREATE_ARTIST_START = "CREATE_ARTIST_START";
export const CREATE_ARTIST_SUCCESS: CREATE_ARTIST_SUCCESS = "CREATE_ARTIST_SUCCESS";
export const CREATE_ARTIST_FAIL: CREATE_ARTIST_FAIL = "CREATE_ARTIST_FAIL";

export type FETCH_ARTISTS_START = "FETCH_ARTISTS_START";
export type FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";
export type FETCH_ARTISTS_FAIL = "FETCH_ARTISTS_FAIL";

export const FETCH_ARTISTS_START: FETCH_ARTISTS_START = "FETCH_ARTISTS_START";
export const FETCH_ARTISTS_SUCCESS: FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";
export const FETCH_ARTISTS_FAIL: FETCH_ARTISTS_FAIL = "FETCH_ARTISTS_FAIL";
