export type CREATE_ARTIST = "CREATE_ARTIST";
export type CREATE_ARTIST_SUCCESS = "CREATE_ARTIST_SUCCESS";
export type CREATE_ARTIST_FAIL = "CREATE_ARTIST_FAIL";

export const CREATE_ARTIST: CREATE_ARTIST = "CREATE_ARTIST";
export const CREATE_ARTIST_SUCCESS: CREATE_ARTIST_SUCCESS = "CREATE_ARTIST_SUCCESS";
export const CREATE_ARTIST_FAIL: CREATE_ARTIST_FAIL = "CREATE_ARTIST_FAIL";

export type FETCH_ARTISTS = "FETCH_ARTISTS"
export type FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";
export type FETCH_ARTISTS_FAIL = "FETCH_ARTISTS_FAIL";

export const FETCH_ARTISTS: FETCH_ARTISTS = "FETCH_ARTISTS";
export const FETCH_ARTISTS_SUCCESS: FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";
export const FETCH_ARTISTS_FAIL: FETCH_ARTISTS_FAIL = "FETCH_ARTISTS_FAIL";
